### ISSUE TITLE
SUGESTÃO: Colocar o nome do "locatário" na devolução

### ISSUE THREAD

**Issue by dvalenca** [Ameciclo/botaprarodar#65]
Na devolução da bicicleta aparece a foto da bicicleta, o nome desta, o número de ordem e o número de série.

O número de série não é tão útil nesse momento e falta o nome do locatário. Portanto, sugiro trocar o campo número de série por locatário nesse primeiro passo.

Sugestão de formato:
[Número de Série]. [Nome da bicicleta]
[Nome do locatário]

Exemplo
01. Praieira
Daniel Valença

Além da foto da bicicleta no início. Talvez a da pessoa, mas aí num sei quanto performance.

**Comment by antoni-sgz-tw** [comment]
Funcionalidade atentida no PR #70
